import fcntl
import os
import re
import sys

from herdr_api import (
    BAR_ROWS, MINIMIZED_FLAG, PLUGIN_ID, PLUGIN_ROOT, STATE_DIR, VERTICAL_FLAG, HerdrError,
    call, fit_bar, in_plugin_root, is_minimized, is_vertical, read_registry, set_flag,
    snapshot, write_registry,
)

MARKER = "# Generated by the bottombar plugin"
MARKER_RE = re.compile(r"^# Generated by the bottombar plugin from (.+) for the vertical layout;")
BASE_SUFFIX = ".bottombar-base"
DEFAULT_SIDEBAR_KEY = "prefix+b"
SIDEBAR_KEY_RE = re.compile(r"""^\s*toggle_sidebar\s*=\s*["']([^"']*)["']""")
UI_OVERRIDES = [
    ("sidebar_width", "0"),
    ("sidebar_min_width", "0"),
    ("sidebar_max_width", "0"),
    ("sidebar_collapsed_mode", '"hidden"'),
    ("pane_outer_borders", "false"),
    ("pane_gaps", "false"),
    ("tab_bar_position", '"bottom"'),
]
STATUS_ENTRY = (
    "tab_bar_right",
    '[{ type = "command", command = "/usr/bin/python3 -B \'%s\'", interval_seconds = 2, '
    'timeout_seconds = 2 }]' % os.path.join(PLUGIN_ROOT, "herdr", "status.py"),
)
KEY_OVERRIDES = [("toggle_sidebar", '""')]


def config_path():
    return os.environ.get("HERDR_CONFIG_PATH") or os.path.expanduser("~/.config/herdr/config.toml")


def overlay(text, minimized, base):
    """`text` with the vertical layout's settings laid over it, and the sidebar's key moved to minimize."""
    ui = UI_OVERRIDES + ([STATUS_ENTRY] if minimized else [])
    tables = {"keys": KEY_OVERRIDES, "ui": ui}
    out = ["%s from %s for the vertical layout; edit that file instead." % (MARKER, base), ""]
    current = None
    seen = set()
    sidebar_key = DEFAULT_SIDEBAR_KEY
    for line in text.splitlines():
        stripped = line.split("#", 1)[0].strip()
        if stripped.startswith("["):
            current = None if stripped.startswith("[[") else stripped.strip("[]").strip()
            out.append(line)
            if current in tables:
                seen.add(current)
                out.extend("%s = %s" % kv for kv in tables[current])
            continue
        if current == "keys":
            m = SIDEBAR_KEY_RE.match(line)
            if m:
                sidebar_key = m.group(1)
        if current in tables and "=" in stripped:
            if stripped.split("=", 1)[0].strip() in dict(tables[current]):
                continue
        out.append(line)
    for name, kvs in tables.items():
        if name not in seen:
            out += ["", "[%s]" % name] + ["%s = %s" % kv for kv in kvs]
    if sidebar_key:
        out += [
            "",
            "[[keys.command]]",
            'key = "%s"' % sidebar_key,
            'type = "plugin_action"',
            'command = "%s.minimize"' % PLUGIN_ID,
            'description = "Fold the bottom bar into the tab bar, or unfold it"',
        ]
    return "\n".join(out) + "\n"


def generated_from(path):
    """The base config `path` was generated from, or None when `path` is not generated."""
    try:
        with open(path) as f:
            m = MARKER_RE.match(f.readline())
    except OSError:
        return None
    return m.group(1) if m else None


def replace_with(path, make):
    tmp = path + ".bottombar.tmp"
    if os.path.lexists(tmp):
        os.remove(tmp)
    make(tmp)
    os.replace(tmp, path)


def write_file(path, text):
    with open(path, "w") as f:
        f.write(text)


def apply_config(vertical, minimized):
    """Swap herdr's config for its vertical overlay, or put the user's own back; True when it changed.

    A symlinked config is remembered by its target and relinked on the way back. A regular file
    is set aside as `config.toml.bottombar-base` and moved back.
    """
    path = config_path()
    set_aside = path + BASE_SUFFIX
    base = generated_from(path)
    if not vertical:
        if base is None:
            return False
        if base == set_aside:
            os.replace(set_aside, path)
        else:
            replace_with(path, lambda tmp: os.symlink(base, tmp))
        return True
    adopting = base is None
    if adopting:
        if os.path.islink(path):
            base = os.path.normpath(os.path.join(os.path.dirname(path), os.readlink(path)))
        else:
            base = set_aside
            if os.path.lexists(set_aside):
                print("bottombar: %s already exists; move it away to switch layouts" % set_aside,
                      file=sys.stderr)
                return False
    source = path if adopting and base == set_aside else base
    try:
        with open(source) as f:
            text = f.read()
    except FileNotFoundError:
        text = ""
    want = overlay(text, minimized, base)
    if not adopting:
        with open(path) as f:
            if f.read() == want:
                return False
    if adopting and base == set_aside:
        if os.path.exists(path):
            os.replace(path, set_aside)
        else:
            write_file(set_aside, "")
    replace_with(path, lambda tmp: write_file(tmp, want))
    return True


def reload_config():
    try:
        result = call("server.reload_config")
    except (OSError, HerdrError) as e:
        print("bottombar: reload: %s" % e, file=sys.stderr)
        return
    for line in result.get("diagnostics") or []:
        print("bottombar: config: %s" % line, file=sys.stderr)


def bar_alive(pane_id):
    try:
        info = call("pane.process_info", {"pane_id": pane_id})["process_info"]
    except (OSError, HerdrError):
        return False
    for proc in info.get("foreground_processes", []):
        if any(arg.endswith("panel.py") for arg in proc.get("argv") or []):
            return True
    return False


def close(pane_id):
    try:
        call("pane.close", {"pane_id": pane_id})
    except (OSError, HerdrError):
        pass


def add_bar(layout):
    if layout.get("zoomed"):
        return None
    panes = layout.get("panes", [])
    if not panes:
        return None
    bottom = max(p["rect"]["y"] + p["rect"]["height"] for p in panes)
    edge = [p for p in panes if p["rect"]["y"] + p["rect"]["height"] == bottom]
    target = max(edge, key=lambda p: (p["rect"]["width"], -p["rect"]["x"]))
    height = target["rect"]["height"]
    if height < (BAR_ROWS + 2) * 2:
        return None
    opened = call("plugin.pane.open", {
        "plugin_id": PLUGIN_ID,
        "entrypoint": "bar",
        "placement": "split",
        "target_pane_id": target["pane_id"],
        "direction": "down",
        "focus": False,
    })
    bar_id = opened["plugin_pane"]["pane"]["pane_id"]
    call("pane.rename", {"pane_id": bar_id, "label": None})
    fit_bar(layout["tab_id"], bar_id, height, BAR_ROWS + 1)
    return bar_id


def sync():
    os.makedirs(STATE_DIR, exist_ok=True)
    with open(os.path.join(STATE_DIR, "lock"), "w") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        vertical = is_vertical()
        if apply_config(vertical, is_minimized()):
            reload_config()
        wanted = vertical and not is_minimized()
        snap = snapshot()
        registry = read_registry()
        kept = {}
        closed = False
        for pane in snap.get("panes", []):
            pane_id = pane["pane_id"]
            if pane_id not in registry and not in_plugin_root(pane):
                continue
            alive = bar_alive(pane_id)
            if not alive and pane_id not in registry:
                continue
            if not wanted or not alive or pane["tab_id"] in kept:
                close(pane_id)
                closed = True
            else:
                kept[pane["tab_id"]] = pane_id
        if wanted:
            if closed:
                snap = snapshot()
            for layout in snap.get("layouts", []):
                if layout["tab_id"] in kept:
                    continue
                try:
                    bar_id = add_bar(layout)
                except (OSError, HerdrError) as e:
                    print("bottombar: %s: %s" % (layout["tab_id"], e), file=sys.stderr)
                    continue
                if bar_id:
                    kept[layout["tab_id"]] = bar_id
        write_registry(kept.values())


def layout():
    set_flag(VERTICAL_FLAG, not is_vertical())
    sync()


def minimize():
    if not is_vertical():
        return
    set_flag(MINIMIZED_FLAG, not is_minimized())
    sync()


if __name__ == "__main__":
    {"sync": sync, "layout": layout, "minimize": minimize}[sys.argv[1]]()
